{% set name = "lb-nightly-configuration" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-configuration-{{ version }}.tar.gz
  sha256: 39f760cd8f896868e5b49f4602c453ad2a156cb9db87a810d1f13a0df43d3548

build:
  number: 0
  noarch: python
  entry_points:
    - lbn-check-config = lb.nightly.configuration:check_config
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - configurator >=2.6.0,<3.0.0
    - gitpython >=3.1.18,<4.0.0
    - python >=3.6,<4.0
    - pyyaml >=6.0,<7.0
    - tabulate >=0.8.9,<0.9.0

test:
  imports:
    - lb
    - lb.nightly.configuration
  commands:
    - pip check
    - lbn-check-config --help
  requires:
    - pip

about:
  home: https://pypi.org/project/lb-nightly-configuration/
  summary: classes and functions to suppot the LHCb Nightly Build System configuration
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maszyman
